site_name: AB testing with GTM
site_url: https://abtesting.sandervolbeda.com/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle: 
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
   - 'index.md'
   - 'setup.md'
   - 'targetting.md' 
   - 'analyses.md'
   - 'splittest.md'
   - 'development.md'

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/sandervolbeda
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/SanderVolbeda
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sandervolbeda/

markdown_extensions:
  - pymdownx.highlight: 
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://sandervolbeda.com/"  target="_blank" rel="noopener">Sander Volbeda</a>